# Installing TensorLy

In [1]:
pip install -U tensorly


     |████████████████████████████████| 71kB 3.4MB/s 
     |████████████████████████████████| 163kB 13.3MB/s 
  Created wheel for tensorly: filename=tensorly-0.4.5-cp36-none-any.whl size=100154 sha256=405a93c370686ec01f182f0013edd6faf6b8875d14f35a0613cb07312f22346e
  Stored in directory: /root/.cache/pip/wheels/44/ae/02/8d00229a4fd0af192b48d24da903f9975c7ac10e706685fc39
Successfully built tensorly


In [0]:
import numpy as np
import torch

In [0]:
X = torch.tensor(np.arange(24).reshape(3,4,2), dtype = torch.float32)

In [11]:
X

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.]],

        [[ 8.,  9.],
         [10., 11.],
         [12., 13.],
         [14., 15.]],

        [[16., 17.],
         [18., 19.],
         [20., 21.],
         [22., 23.]]])

In [0]:
import tensorly as tl

In [0]:
Y = tl.tensor(np.arange(24).reshape(4,3,2), dtype = tl.float32)

In [16]:
Y

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.]],

       [[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]],

       [[12., 13.],
        [14., 15.],
        [16., 17.]],

       [[18., 19.],
        [20., 21.],
        [22., 23.]]], dtype=float32)

In [17]:
Y[:,:,0]

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.],
       [12., 14., 16.],
       [18., 20., 22.]], dtype=float32)

In [18]:
X[:,:,0]

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.]])

In [19]:
type(X)

torch.Tensor

In [20]:
type(Y)

numpy.ndarray

In [0]:
tl.set_backend('pytorch')

In [23]:
X = tl.tensor(np.arange(24).reshape(3,4,2), dtype = tl.float32)
type(X)

torch.Tensor

In [0]:
tl.set_backend('numpy')

In [26]:
X = tl.tensor(np.arange(24).reshape(3,4,2), dtype = tl.float32)
type(X)

numpy.ndarray

In [27]:
X.shape

(3, 4, 2)

In [29]:
tl.unfold(X, mode = 1)

array([[ 0.,  1.,  8.,  9., 16., 17.],
       [ 2.,  3., 10., 11., 18., 19.],
       [ 4.,  5., 12., 13., 20., 21.],
       [ 6.,  7., 14., 15., 22., 23.]], dtype=float32)

In [31]:
tl.unfold(X, mode = 0)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21., 22., 23.]], dtype=float32)

In [32]:
tl.unfold(X, mode = 2)

array([[ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22.],
       [ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23.]],
      dtype=float32)

In [0]:
unfolding = tl.unfold(X, 1)

In [0]:
shape = X.shape

In [38]:
tl.fold(unfolding, mode = 1, shape = shape)

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]], dtype=float32)

In [0]:
M = tl.tensor(np.arange(4*5).reshape(5,4))

In [41]:
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [0]:
res = tl.tenalg.mode_dot(X,M, mode = 1)

In [43]:
res

array([[[  28.,   34.],
        [  76.,   98.],
        [ 124.,  162.],
        [ 172.,  226.],
        [ 220.,  290.]],

       [[  76.,   82.],
        [ 252.,  274.],
        [ 428.,  466.],
        [ 604.,  658.],
        [ 780.,  850.]],

       [[ 124.,  130.],
        [ 428.,  450.],
        [ 732.,  770.],
        [1036., 1090.],
        [1340., 1410.]]])

In [44]:
res.shape

(3, 5, 2)

In [48]:
M.shape

(5, 4)

In [49]:
X.shape

(3, 4, 2)

In [52]:
X

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]], dtype=float32)

In [54]:
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [0]:
v = tl.tensor(np.arange(4))

In [59]:
X[:,:,0] @v

array([ 28.,  76., 124.])

In [63]:
np.stack( [X[:,:,0] @ v, X[:,:,1] @ v]).T

array([[ 28.,  34.],
       [ 76.,  82.],
       [124., 130.]])